// Generated by gencpp from file nodelet/NodeletLoad.msg
// DO NOT EDIT!


#ifndef NODELET_MESSAGE_NODELETLOAD_H
#define NODELET_MESSAGE_NODELETLOAD_H

#include <ros/service_traits.h>


#include <nodelet/NodeletLoadRequest.h>
#include <nodelet/NodeletLoadResponse.h>


namespace nodelet
{

struct NodeletLoad
{

typedef NodeletLoadRequest Request;
typedef NodeletLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NodeletLoad
} // namespace nodelet


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodelet::NodeletLoad > {
  static const char* value()
  {
    return "8cfbf33bf3fbd4c54a833f6e2b105331";
  }

  static const char* value(const ::nodelet::NodeletLoad&) { return value(); }
};

template<>
struct DataType< ::nodelet::NodeletLoad > {
  static const char* value()
  {
    return "nodelet/NodeletLoad";
  }

  static const char* value(const ::nodelet::NodeletLoad&) { return value(); }
};


// service_traits::MD5Sum< ::nodelet::NodeletLoadRequest> should match 
// service_traits::MD5Sum< ::nodelet::NodeletLoad > 
template<>
struct MD5Sum< ::nodelet::NodeletLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodelet::NodeletLoad >::value();
  }
  static const char* value(const ::nodelet::NodeletLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodelet::NodeletLoadRequest> should match 
// service_traits::DataType< ::nodelet::NodeletLoad > 
template<>
struct DataType< ::nodelet::NodeletLoadRequest>
{
  static const char* value()
  {
    return DataType< ::nodelet::NodeletLoad >::value();
  }
  static const char* value(const ::nodelet::NodeletLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodelet::NodeletLoadResponse> should match 
// service_traits::MD5Sum< ::nodelet::NodeletLoad > 
template<>
struct MD5Sum< ::nodelet::NodeletLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodelet::NodeletLoad >::value();
  }
  static const char* value(const ::nodelet::NodeletLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodelet::NodeletLoadResponse> should match 
// service_traits::DataType< ::nodelet::NodeletLoad > 
template<>
struct DataType< ::nodelet::NodeletLoadResponse>
{
  static const char* value()
  {
    return DataType< ::nodelet::NodeletLoad >::value();
  }
  static const char* value(const ::nodelet::NodeletLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODELET_MESSAGE_NODELETLOAD_H
