// Generated by gencpp from file nodelet/NodeletList.msg
// DO NOT EDIT!


#ifndef NODELET_MESSAGE_NODELETLIST_H
#define NODELET_MESSAGE_NODELETLIST_H

#include <ros/service_traits.h>


#include <nodelet/NodeletListRequest.h>
#include <nodelet/NodeletListResponse.h>


namespace nodelet
{

struct NodeletList
{

typedef NodeletListRequest Request;
typedef NodeletListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NodeletList
} // namespace nodelet


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodelet::NodeletList > {
  static const char* value()
  {
    return "99c7b10e794f5600b8030e697e946ca7";
  }

  static const char* value(const ::nodelet::NodeletList&) { return value(); }
};

template<>
struct DataType< ::nodelet::NodeletList > {
  static const char* value()
  {
    return "nodelet/NodeletList";
  }

  static const char* value(const ::nodelet::NodeletList&) { return value(); }
};


// service_traits::MD5Sum< ::nodelet::NodeletListRequest> should match 
// service_traits::MD5Sum< ::nodelet::NodeletList > 
template<>
struct MD5Sum< ::nodelet::NodeletListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodelet::NodeletListRequest> should match 
// service_traits::DataType< ::nodelet::NodeletList > 
template<>
struct DataType< ::nodelet::NodeletListRequest>
{
  static const char* value()
  {
    return DataType< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodelet::NodeletListResponse> should match 
// service_traits::MD5Sum< ::nodelet::NodeletList > 
template<>
struct MD5Sum< ::nodelet::NodeletListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodelet::NodeletListResponse> should match 
// service_traits::DataType< ::nodelet::NodeletList > 
template<>
struct DataType< ::nodelet::NodeletListResponse>
{
  static const char* value()
  {
    return DataType< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODELET_MESSAGE_NODELETLIST_H
